### ISSUE TITLE
feat(nft-exchange-api):  fetching all auctions/bids return only active ones

### ISSUE THREAD

**Issue by amacar** [protokol/nft#80]
# 🚀 feature request

### Relevant Package
This feature request is for @protokol/nft-exchange-api

### Description
When you fetch all auctions/bids (`.../api/nft/exchange/auctions`/`.../api/nft/exchange/bids`) return only active ones.

### Describe the solution you'd like
It would be nice to return only active ones when fetching all auctions/bids.

**Comment by kristjank** [comment]
@amacar this can be closed right?

**Comment by kristjank** [comment]
Waiting for more flexibility from the custom transaction history service - to be added within core after TransactionHistory refactor

**Comment by amacar** [comment]
Moved to the internal issue tracker.
